<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{

    // requete sql sur mesure;

    /**
     * @param $date
     * @return Event[]
     */
    public function findAllGreaterThanDate($date)
    {

        $qb = $this->createQueryBuilder('e')
            ->andWhere('e.date > :date')
            ->setParameter('date',$date )
            ->getQuery();

        return $qb->execute();


    }

    // // plus utilisé
    // /**
    //  * @param $date,$place
    //  * @return Event[]
    //  */
    // public function findByPlace($date,$place)
    // {

    //     $qb = $this->createQueryBuilder('e')
    //         ->where('e.date > :date')
    //         ->andWhere('e.place like :place')
    //         ->setParameter('date',$date )
    //         ->setParameter('place',"%".$place."%" )
    //         ->getQuery();

    //     return $qb->execute();

    // }


    //  // plus utilisé
    // /**
    //  * @param $date,$theme
    //  * @return Event[]
    //  */
    // public function findByTheme($date,$theme)
    // {
   
    //     $qb = $this->createQueryBuilder('e')
    //         ->where('e.date > :date')
    //         ->andWhere('e.theme like :theme')
    //         ->setParameter('date',$date )
    //         ->setParameter('theme',"%".$theme."%" )
    //         ->getQuery();

    //     return $qb->execute();

    // }

    // nouveau filtre 
    /**
     * @param $date,$theme
     * @return Event[]
     */
    public function findByFilter($dateNow, $title, $place, $date, $theme)
    {
   
        $qb = $this->createQueryBuilder('e')
            ->where('e.date > :dateNow')
            ->andWhere('e.title like :title')
            ->andWhere('e.theme like :theme')
            ->andWhere('e.place like :place')
            ->andWhere('e.date > :date')
            ->setParameter('dateNow',$dateNow )
            ->setParameter('theme',"%".$theme."%" )
            ->setParameter('place',"%".$place."%" )
            ->setParameter('date',$date)
            ->setParameter('title',"%".$title."%" )
            ->getQuery();

        return $qb->execute();

    }

}
